def Boston Celtics()
  st.header('Boston Celtics')
  st.write('Boston Celtics(1946年-至今)')
  col1, col2,col3= st.columns(3)
  col1.metric("冠軍🏆", "1  次")
  col2.metric("聯盟冠軍🏆", "22  次")
  col3.metric("分組冠軍🏆", "32  次")
